package io.github.pos.corba.hello;


/**
* hello/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Terça-feira, 7 de Fevereiro de 2017 16h23min38s BRT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
